### ISSUE TITLE
The program has unexpectedly finished.

### ISSUE THREAD

**Issue by thisiseddy-ab** [RSATom/QmlVlc#83]
I have no Idea why wont start, it just shown some warning:

 warning: C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
maybe is this the reason
it just unexpectedly finishe
![errorvlcc](https://user-images.githubusercontent.com/66516635/134351210-1569dc32-0c6e-49c9-9fe7-04461bef141a.png)
s

**Comment by RSATom** [comment]
1. Are you trying to use https://github.com/RSATom/QmlVlcDemo ?
2. Do you have VLC in your PATH?

**Comment by thisiseddy-ab** [comment]
yes 
 im yousing Vlc Demo

do you need vlc in your path , how it suppose to work in android then ?

**Comment by RSATom** [comment]
on Android libvlc should be placed inside app package.

**Comment by thisiseddy-ab** [comment]
if fix it but do you know how to add seperate audio and subtitle ?

**Comment by RSATom** [comment]
https://github.com/RSATom/QmlVlc/wiki/QmlVlc-API

**Comment by thisiseddy-ab** [comment]
I have another problem now wont start in android, it work at first time now wont work

Output:
I art     : Late-enabling -Xcheck:jni
W System  : ClassLoader referenced unknown path:
I QtCore  : Start
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5Gui.so: unused DT entry: type 0x1d arg 0x59a95
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5Gui.so: unsupported flags DT_FLAGS_1=0x80
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5Network.so: unused DT entry: type 0x1d arg 0x14a2d
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5Network.so: unsupported flags DT_FLAGS_1=0x80
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5Multimedia.so: unused DT entry: type 0x1d arg 0x18931
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5Multimedia.so: unsupported flags DT_FLAGS_1=0x80
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5Qml.so: unused DT entry: type 0x1d arg 0x32d63
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5Qml.so: unsupported flags DT_FLAGS_1=0x80
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5Quick.so: unused DT entry: type 0x1d arg 0x4b3b2
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5Quick.so: unsupported flags DT_FLAGS_1=0x80
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5MultimediaQuick.so: unused DT entry: type 0x1d arg 0x3373
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5MultimediaQuick.so: unsupported flags DT_FLAGS_1=0x80
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5QuickParticles.so: unused DT entry: type 0x1d arg 0x54e0
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQt5QuickParticles.so: unsupported flags DT_FLAGS_1=0x80
W linker  : /data/data/org.qtproject.example.QmlVlcDemo/qt-reserved-files/plugins/bearer/libqandroidbearer.so: unused DT entry: type 0x1d arg 0x1738
W linker  : /data/data/org.qtproject.example.QmlVlcDemo/qt-reserved-files/plugins/bearer/libqandroidbearer.so: unsupported flags DT_FLAGS_1=0x80
W linker  : /data/data/org.qtproject.example.QmlVlcDemo/qt-reserved-files/plugins/platforms/android/libqtforandroid.so: unused DT entry: type 0x1d arg 0x9d7b
W linker  : /data/data/org.qtproject.example.QmlVlcDemo/qt-reserved-files/plugins/platforms/android/libqtforandroid.so: unsupported flags DT_FLAGS_1=0x80
I Qt      : qt started
W linker  : /data/data/org.qtproject.example.QmlVlcDemo/qt-reserved-files/plugins/mediaservice/libqtmedia_android.so: unused DT entry: type 0x1d arg 0x58ed
W linker  : /data/data/org.qtproject.example.QmlVlcDemo/qt-reserved-files/plugins/mediaservice/libqtmedia_android.so: unsupported flags DT_FLAGS_1=0x80
I Qt JAVA : Can't find '/data/data/org.qtproject.example.QmlVlcDemo/qt-reserved-files/lib/libQt5MultimediaQuick.so'
I Qt JAVA : Can't find '/data/data/org.qtproject.example.QmlVlcDemo/qt-reserved-files/lib/libQt5QuickParticles.so'
I art     : Background sticky concurrent mark sweep GC freed 12233(1350KB) AllocSpace objects, 2(40KB) LOS objects, 72% free, 993KB/3MB, paused 2.245ms total 105.493ms
W art     : Suspending all threads took: 39.715ms
I art     : Background sticky concurrent mark sweep GC freed 3926(613KB) AllocSpace objects, 8(176KB) LOS objects, 20% free, 3MB/4MB, paused 41.506ms total 96.108ms
W linker  : /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libQmlVlcDemo.so: unused DT entry: type 0x1d arg 0x20c49
W System.err: java.lang.Exception:
W System.err: 	at org.qtproject.qt5.android.bindings.QtLoader.loadApplication(QtLoader.java:243)
W System.err: 	at org.qtproject.qt5.android.bindings.QtLoader.startApp(QtLoader.java:697)
W System.err: 	at org.qtproject.qt5.android.bindings.QtActivityLoader.onCreate(QtActivityLoader.java:166)
W System.err: 	at org.qtproject.qt5.android.bindings.QtActivity.onCreateHook(QtActivity.java:266)
W System.err: 	at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:273)
W System.err: 	at android.app.Activity.performCreate(Activity.java:6237)
W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
W System.err: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
W System.err: 	at android.os.Looper.loop(Looper.java:148)
W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E AndroidRuntime: FATAL EXCEPTION: qtMainLoopThread
E AndroidRuntime: Process: org.qtproject.example.QmlVlcDemo, PID: 4380
E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/org.qtproject.example.QmlVlcDemo-1/lib/arm/libvlcjni.so: has text relocations
E AndroidRuntime: 	at java.lang.Runtime.load(Runtime.java:332)
E AndroidRuntime: 	at java.lang.System.load(System.java:1069)
E AndroidRuntime: 	at org.qtproject.qt5.android.QtNative$4.run(QtNative.java:259)
E AndroidRuntime: 	at org.qtproject.qt5.android.QtThread$2.run(QtThread.java:88)
E AndroidRuntime: 	at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D         : HostConnection::get() New Host Connection established 0xad54f5e0, tid 4380
I Choreographer: Skipped 53 frames!  The application may be doing too much work on its main thread.
09-25 14:22:54.437  4380  4380 E WindowManager:
E WindowManager: android.view.WindowLeaked: Activity org.qtproject.qt5.android.bindings.QtActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{260985c V.E...... R.....ID 0,0-1056,272} that was originally added here
E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
E WindowManager: 	at android.app.Dialog.show(Dialog.java:319)
E WindowManager: 	at org.qtproject.qt5.android.bindings.QtLoader.loadApplication(QtLoader.java:265)
E WindowManager: 	at org.qtproject.qt5.android.bindings.QtLoader.startApp(QtLoader.java:697)
E WindowManager: 	at org.qtproject.qt5.android.bindings.QtActivityLoader.onCreate(QtActivityLoader.java:166)
E WindowManager: 	at org.qtproject.qt5.android.bindings.QtActivity.onCreateHook(QtActivity.java:266)
E WindowManager: 	at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:273)
E WindowManager: 	at android.app.Activity.performCreate(Activity.java:6237)
E WindowManager: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
E WindowManager: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
E WindowManager: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
E WindowManager: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
E WindowManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E WindowManager: 	at android.os.Looper.loop(Looper.java:148)
E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
E WindowManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
I Process : Sending signal. PID: 4380 SIG: 9

**Comment by thisiseddy-ab** [comment]
I Qt JAVA : Can't find '/data/data/org.qtproject.example/qt-reserved-files/lib/libQt5MultimediaQuick.so'
I Qt JAVA : Can't find '/data/data/org.qtproject.example/qt-reserved-files/lib/libQt5QuickParticles.so'

**Comment by RSATom** [comment]
I don't know. I didn't use this lib long time already.
